name: Run Unit Tests against source files included in a Pull Request targeting the main branch
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ ! startsWith(github.head_ref, 'release') }}
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Identify changes in source files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'fuzzy_parser/**'
              - 'fuzzy_parser/**/*'
      - name: Run Unit Tests if change in source files is detected
        if: steps.changes.outputs.src == 'true'
        run: sudo make utilities && make test
