name: Create a new release based on current version
on:
  pull_request:
    types: [ closed ]
    branches:
      - master
jobs:
  release:
    name: Create a new release based on current version
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Library Repository
        uses: actions/checkout@master
      - name: Ensure that all necessary packages for the workflow are installed before proceeding
        run: sudo make packages
      - name: Build a binary wheel, a source tarball, and publish distribution 📦 to PyPI
        run: make TOKEN=${{ secrets.PYPI_API_TOKEN }} release
